// Local

// recipes
GET http://localhost:8080/recipes
###
GET http://localhost:8080/recipes/65c878aae78e5632ba80cd94

### Create
POST http://localhost:8080/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Pound Cake",
    "ingredients": "1lb sugar, 1lb butter, 1lb flour, 1 dozen eggs, 1/4 teaspoon salt, 1/4 cup fresh lemon juice, 1 tablespoon fresh lemon rind, grated",
    "directions": "1. Preheat oven to 325 deg F\\n2. In mixing bowl cream butter and sugar\\n3. Add 1 egg at a time beating after each\\n4. Gradually add sifted flour, 1/2 cup at a time, till all blended\\n5. Add lemon juice and lemon rind, blend\\n6. Pour into a buttered and floured tube pan\\n7. Bake 75 to 90 minutes; Till toothpick in center comes out clean.",
    "cuisine": "cake",
    "chef": "John Smith",
    "creation": "1700s"
}

### Edit
PUT http://localhost:8080/recipes/65c9b6f696fcbb7ae75906d2 HTTP/1.1
Content-Type: application/json

{
    "title": "Pound Cake v2",
    "ingredients": "1lb sugar, 1lb butter, 1lb flour, 1 dozen eggs, 1/4 teaspoon salt, 1/4 cup fresh lemon juice, 1 tablespoon fresh lemon rind, grated",
    "directions": "1. Preheat oven to 325 deg F\\n2. In mixing bowl cream butter and sugar\\n3. Add 1 egg at a time beating after each\\n4. Gradually add sifted flour, 1/2 cup at a time, till all blended\\n5. Add lemon juice and lemon rind, blend\\n6. Pour into a buttered and floured tube pan\\n7. Bake 75 to 90 minutes; Till toothpick in center comes out clean.",
    "cuisine": "cake",
    "chef": "John Smith",
    "creation": "1800s"
}

### Delete
DELETE http://localhost:8080/recipes/65c9b6f696fcbb7ae75906d2 HTTP/1.1

// Chefs
###
GET http://localhost:8080/chefs
###
GET http://localhost:8080/chefs/65d98d29814c1e602ce61d7a

### Create
POST http://localhost:8080/chefs HTTP/1.1
Content-Type: application/json

{
    "firstName": "Eric",
    "lastName": "Martinez",
    "cuisine": "Mexican",
    "forHire": "true",
    "email": "test@chefs.com"
}

### Edit
PUT http://localhost:8080/chefs/65c9b6f696fcbb7ae75906d2 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Eric",
    "lastName": "Martinez",
    "cuisine": "Mexican",
    "forHire": "false",
    "email": "test@chefs.com",
    "phone": "1234567890"
}

### Delete
DELETE http://localhost:8080/chefs/65d98d29814c1e602ce61d7a HTTP/1.1


// Render
###
GET https://recipe-api-ma9i.onrender.com/
###
GET https://recipe-api-ma9i.onrender.com/recipes
###
GET https://recipe-api-ma9i.onrender.com/recipes/65c9b68196fcbb7ae75906d1
### create new
POST https://recipe-api-ma9i.onrender.com/recipes/ HTTP/1.1
Content-Type: application/json

{
    "title": "Pound Cake",
    "ingredients": "1lb sugar, 1lb butter, 1lb flour, 1 dozen eggs, 1/4 teaspoon salt, 1/4 cup fresh lemon juice, 1 tablespoon fresh lemon rind, grated",
    "directions": "1. Preheat oven to 325 deg F\\n2. In mixing bowl cream butter and sugar\\n3. Add 1 egg at a time beating after each\\n4. Gradually add sifted flour, 1/2 cup at a time, till all blended\\n5. Add lemon juice and lemon rind, blend\\n6. Pour into a buttered and floured tube pan\\n7. Bake 75 to 90 minutes; Till toothpick in center comes out clean.",
    "cuisine": "cake",
    "chef": "John Smith",
    "creation": "1700s"
}

### update
PUT https://recipe-api-ma9i.onrender.com/recipes/65c9bdd178f02fb0500c351a HTTP/1.1
Content-Type: application/json

{
    "title": "Pound Cake v2",
    "ingredients": "1lb sugar, 1lb butter, 1lb flour, 1 dozen eggs, 1/4 teaspoon salt, 1/4 cup fresh lemon juice, 1 tablespoon fresh lemon rind, grated",
    "directions": "1. Preheat oven to 325 deg F\\n2. In mixing bowl cream butter and sugar\\n3. Add 1 egg at a time beating after each\\n4. Gradually add sifted flour, 1/2 cup at a time, till all blended\\n5. Add lemon juice and lemon rind, blend\\n6. Pour into a buttered and floured tube pan\\n7. Bake 75 to 90 minutes; Till toothpick in center comes out clean.",
    "cuisine": "cake",
    "chef": "John Smith",
    "creation": "1800s"
}

### Delete Contact
DELETE https://recipe-api-ma9i.onrender.com/recipes/65c9bdd178f02fb0500c351a HTTP/1.1

// Chefs
### 
GET https://recipe-api-ma9i.onrender.com/chefs
###
GET https://recipe-api-ma9i.onrender.com/chefs/65dae335454cb033a9dd066d

### Create
POST https://recipe-api-ma9i.onrender.com/chefs HTTP/1.1
Content-Type: application/json

{
    "firstName": "Eric",
    "lastName": "Martinez",
    "cuisine": "Mexican",
    "forHire": "true"
}

### Edit
PUT https://recipe-api-ma9i.onrender.com/chefs/65dae335454cb033a9dd066d HTTP/1.1
Content-Type: application/json

{
    "firstName": "Eric",
    "lastName": "Martinez",
    "cuisine": "Mexican",
    "forHire": "false",
    "email": "test@chefs.com",
    "phone": "1234567890"
}

### Delete
DELETE https://recipe-api-ma9i.onrender.com/chefs/65dae335454cb033a9dd066d HTTP/1.1